pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
      stage('Database') {
    agent {
        docker {
            image 'mysql:latest'
            args '-e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=testdb -p 3306:3306'
        }
    }
    steps {
        sh 'mysql --version'  // just checks MySQL client inside container
        // Example: Run SQL if you have init.sql in repo
        // sh 'mysql -uroot -proot testdb < init.sql'
    }
}

  }
}
