pipeline {
    agent none

    stages {
        stage('Test Node Version') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'node --version'
            }
        }

        stage('Deploy') {
            agent any  // runs on Jenkins host (must have kubectl installed)
            steps {
                sh 'kubectl apply -f deployment.yml'
            }
        }

        stage('Verify Node Again') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
