pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Deloy') {
      steps {
        sh 'kubectl apply -f deployment.yml'
      }
    }
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
