pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }
    stages {
        stage('Test Node Version') {
            steps {
                sh 'node --version'
            }
        }
        stage('Deploy') {
            steps {
                sh 'kubectl apply -f deployment.yml'
            }
        }
        stage('Verify Node Again') {
            steps {
                sh 'node --version'
            }
        }
    }
}
